import {
    BusinessResponse,
    BusinessType,
    Country,
    CreateBusinessResponse,
    SubscriptionId,
    SubscriptionPlanFeatureStatus,
    SubscriptionResponse,
    ThemeStyle,
    Timezone,
} from '@/types/business-api';
import { PaypalGenerateAccessToken } from '@/types/paypal.types';

export const mswBusiness: BusinessResponse = {
    PK: 'BUSINESS#28f2e562-508d-48e5-89df-e14ac0bcd20b',
    SK: 'BUSINESS_DOMAIN#asd',
    business_images: ['https://www.example.com/image.png'],
    business_type: 'barber-shop',
    country: {
        calling_code: '+506',
        code: 'CR',
        currency: 'CRC',
        name: 'Costa Rica',
    },
    created_at: '2024-09-14T05:25:23.520Z',
    currency: { code: 'CRC', name: 'Costa Rican colón', symbol: '₡' },
    domain: 'asd',
    is_published: false,
    name: 'asd',
    subscription: null,
    subscription_ref: null,
    theme_style: 'brand-colors',
    timezone: {
        gmt: '-01:00',
        name: 'Azores',
        zoneName: 'Atlantic/Azores',
    },
    web_logo: 'https://www.example.com/logo.png',
};

export const mswBusinessTypes: BusinessType[] = [
    {
        id: 'barber-shop',
        name: 'Barber Shop',
    },
    {
        id: 'beauty-salon',
        name: 'Beauty Salon',
    },
    {
        id: 'spa',
        name: 'Spa',
    },
    {
        id: 'pet-grooming',
        name: 'Pet Grooming',
    },
    {
        id: 'dental-clinic',
        name: 'Dental Clinic',
    },
    {
        id: 'medical-clinic',
        name: 'Medical Clinic',
    },
    {
        id: 'gym',
        name: 'Gym',
    },
    {
        id: 'personal-trainer',
        name: 'Personal Trainer',
    },
    {
        id: 'tattoo-studio',
        name: 'Tattoo Studio',
    },
    {
        id: 'professional-consultation',
        name: 'Professional Consultation',
    },
    {
        id: 'other',
        name: 'Other',
    },
];

export const mswCountries: Country[] = [
    {
        calling_code: '+880',
        code: 'BD',
        currency: 'BDT',
        name: 'Bangladesh',
    },
    {
        calling_code: '+32',
        code: 'BE',
        currency: 'EUR',
        name: 'Belgium',
    },
    {
        calling_code: '+226',
        code: 'BF',
        currency: 'XOF',
        name: 'Burkina Faso',
    },
    {
        calling_code: '+359',
        code: 'BG',
        currency: 'BGN',
        name: 'Bulgaria',
    },
    {
        calling_code: '+387',
        code: 'BA',
        currency: 'BAM',
        name: 'Bosnia and Herzegovina',
    },
    {
        calling_code: '+1-246',
        code: 'BB',
        currency: 'BBD',
        name: 'Barbados',
    },
    {
        calling_code: '+673',
        code: 'BN',
        currency: 'BND',
        name: 'Brunei',
    },
    {
        calling_code: '+591',
        code: 'BO',
        currency: 'BOB',
        name: 'Bolivia',
    },
    {
        calling_code: '+973',
        code: 'BH',
        currency: 'BHD',
        name: 'Bahrain',
    },
    {
        calling_code: '+257',
        code: 'BI',
        currency: 'BIF',
        name: 'Burundi',
    },
    {
        calling_code: '+229',
        code: 'BJ',
        currency: 'XOF',
        name: 'Benin',
    },
    {
        calling_code: '+975',
        code: 'BT',
        currency: 'BTN',
        name: 'Bhutan',
    },
    {
        calling_code: '+1-876',
        code: 'JM',
        currency: 'JMD',
        name: 'Jamaica',
    },
    {
        calling_code: '+267',
        code: 'BW',
        currency: 'BWP',
        name: 'Botswana',
    },
    {
        calling_code: '+55',
        code: 'BR',
        currency: 'BRL',
        name: 'Brazil',
    },
    {
        calling_code: '+1-242',
        code: 'BS',
        currency: 'BSD',
        name: 'Bahamas',
    },
    {
        calling_code: '+375',
        code: 'BY',
        currency: 'BYR',
        name: 'Belarus',
    },
    {
        calling_code: '+501',
        code: 'BZ',
        currency: 'BZD',
        name: 'Belize',
    },
    {
        calling_code: '+7',
        code: 'RU',
        currency: 'RUB',
        name: 'Russia',
    },
    {
        calling_code: '+250',
        code: 'RW',
        currency: 'RWF',
        name: 'Rwanda',
    },
    {
        calling_code: '+381',
        code: 'RS',
        currency: 'RSD',
        name: 'Serbia',
    },
    {
        calling_code: '+670',
        code: 'TL',
        currency: 'USD',
        name: 'Timor-Leste',
    },
    {
        calling_code: '+993',
        code: 'TM',
        currency: 'TMT',
        name: 'Turkmenistan',
    },
    {
        calling_code: '+992',
        code: 'TJ',
        currency: 'TJS',
        name: 'Tajikistan',
    },
    {
        calling_code: '+40',
        code: 'RO',
        currency: 'RON',
        name: 'Romania',
    },
    {
        calling_code: '+245',
        code: 'GW',
        currency: 'XOF',
        name: 'Guinea-Bissau',
    },
    {
        calling_code: '+502',
        code: 'GT',
        currency: 'GTQ',
        name: 'Guatemala',
    },
    {
        calling_code: '+30',
        code: 'GR',
        currency: 'EUR',
        name: 'Greece',
    },
    {
        calling_code: '+240',
        code: 'GQ',
        currency: 'XAF',
        name: 'Equatorial Guinea',
    },
    {
        calling_code: '+81',
        code: 'JP',
        currency: 'JPY',
        name: 'Japan',
    },
    {
        calling_code: '+592',
        code: 'GY',
        currency: 'GYD',
        name: 'Guyana',
    },
    {
        calling_code: '+995',
        code: 'GE',
        currency: 'GEL',
        name: 'Georgia',
    },
    {
        calling_code: '+1-473',
        code: 'GD',
        currency: 'XCD',
        name: 'Grenada',
    },
    {
        calling_code: '+44',
        code: 'GB',
        currency: 'GBP',
        name: 'United Kingdom',
    },
    {
        calling_code: '+241',
        code: 'GA',
        currency: 'XAF',
        name: 'Gabon',
    },
    {
        calling_code: '+503',
        code: 'SV',
        currency: 'USD',
        name: 'El Salvador',
    },
    {
        calling_code: '+224',
        code: 'GN',
        currency: 'GNF',
        name: 'Guinea',
    },
    {
        calling_code: '+220',
        code: 'GM',
        currency: 'GMD',
        name: 'Gambia',
    },
    {
        calling_code: '+233',
        code: 'GH',
        currency: 'GHS',
        name: 'Ghana',
    },
    {
        calling_code: '+968',
        code: 'OM',
        currency: 'OMR',
        name: 'Oman',
    },
    {
        calling_code: '+216',
        code: 'TN',
        currency: 'TND',
        name: 'Tunisia',
    },
    {
        calling_code: '+962',
        code: 'JO',
        currency: 'JOD',
        name: 'Jordan',
    },
    {
        calling_code: '+385',
        code: 'HR',
        currency: 'HRK',
        name: 'Croatia',
    },
    {
        calling_code: '+509',
        code: 'HT',
        currency: 'HTG',
        name: 'Haiti',
    },
    {
        calling_code: '+36',
        code: 'HU',
        currency: 'HUF',
        name: 'Hungary',
    },
    {
        calling_code: '+504',
        code: 'HN',
        currency: 'HNL',
        name: 'Honduras',
    },
    {
        calling_code: '+58',
        code: 'VE',
        currency: 'VEF',
        name: 'Venezuela',
    },
    {
        calling_code: '+970',
        code: 'PS',
        currency: 'ILS',
        name: 'Palestinian Territory',
    },
    {
        calling_code: '+680',
        code: 'PW',
        currency: 'USD',
        name: 'Palau',
    },
    {
        calling_code: '+351',
        code: 'PT',
        currency: 'EUR',
        name: 'Portugal',
    },
    {
        calling_code: '+595',
        code: 'PY',
        currency: 'PYG',
        name: 'Paraguay',
    },
    {
        calling_code: '+964',
        code: 'IQ',
        currency: 'IQD',
        name: 'Iraq',
    },
    {
        calling_code: '+507',
        code: 'PA',
        currency: 'PAB',
        name: 'Panama',
    },
    {
        calling_code: '+675',
        code: 'PG',
        currency: 'PGK',
        name: 'Papua New Guinea',
    },
    {
        calling_code: '+51',
        code: 'PE',
        currency: 'PEN',
        name: 'Peru',
    },
    {
        calling_code: '+92',
        code: 'PK',
        currency: 'PKR',
        name: 'Pakistan',
    },
    {
        calling_code: '+63',
        code: 'PH',
        currency: 'PHP',
        name: 'Philippines',
    },
    {
        calling_code: '+48',
        code: 'PL',
        currency: 'PLN',
        name: 'Poland',
    },
    {
        calling_code: '+260',
        code: 'ZM',
        currency: 'ZMK',
        name: 'Zambia',
    },
    {
        calling_code: '+372',
        code: 'EE',
        currency: 'EUR',
        name: 'Estonia',
    },
    {
        calling_code: '+20',
        code: 'EG',
        currency: 'EGP',
        name: 'Egypt',
    },
    {
        calling_code: '+27',
        code: 'ZA',
        currency: 'ZAR',
        name: 'South Africa',
    },
    {
        calling_code: '+593',
        code: 'EC',
        currency: 'USD',
        name: 'Ecuador',
    },
    {
        calling_code: '+39',
        code: 'IT',
        currency: 'EUR',
        name: 'Italy',
    },
    {
        calling_code: '+84',
        code: 'VN',
        currency: 'VND',
        name: 'Vietnam',
    },
    {
        calling_code: '+677',
        code: 'SB',
        currency: 'SBD',
        name: 'Solomon Islands',
    },
    {
        calling_code: '+251',
        code: 'ET',
        currency: 'ETB',
        name: 'Ethiopia',
    },
    {
        calling_code: '+252',
        code: 'SO',
        currency: 'SOS',
        name: 'Somalia',
    },
    {
        calling_code: '+263',
        code: 'ZW',
        currency: 'ZWL',
        name: 'Zimbabwe',
    },
    {
        calling_code: '+966',
        code: 'SA',
        currency: 'SAR',
        name: 'Saudi Arabia',
    },
    {
        calling_code: '+34',
        code: 'ES',
        currency: 'EUR',
        name: 'Spain',
    },
    {
        calling_code: '+291',
        code: 'ER',
        currency: 'ERN',
        name: 'Eritrea',
    },
    {
        calling_code: '+382',
        code: 'ME',
        currency: 'EUR',
        name: 'Montenegro',
    },
    {
        calling_code: '+373',
        code: 'MD',
        currency: 'MDL',
        name: 'Moldova',
    },
    {
        calling_code: '+261',
        code: 'MG',
        currency: 'MGA',
        name: 'Madagascar',
    },
    {
        calling_code: '+212',
        code: 'MA',
        currency: 'MAD',
        name: 'Morocco',
    },
    {
        calling_code: '+377',
        code: 'MC',
        currency: 'EUR',
        name: 'Monaco',
    },
    {
        calling_code: '+998',
        code: 'UZ',
        currency: 'UZS',
        name: 'Uzbekistan',
    },
    {
        calling_code: '+95',
        code: 'MM',
        currency: 'MMK',
        name: 'Myanmar',
    },
    {
        calling_code: '+223',
        code: 'ML',
        currency: 'XOF',
        name: 'Mali',
    },
    {
        calling_code: '+976',
        code: 'MN',
        currency: 'MNT',
        name: 'Mongolia',
    },
    {
        calling_code: '+692',
        code: 'MH',
        currency: 'USD',
        name: 'Marshall Islands',
    },
    {
        calling_code: '+389',
        code: 'MK',
        currency: 'MKD',
        name: 'Macedonia',
    },
    {
        calling_code: '+230',
        code: 'MU',
        currency: 'MUR',
        name: 'Mauritius',
    },
    {
        calling_code: '+356',
        code: 'MT',
        currency: 'EUR',
        name: 'Malta',
    },
    {
        calling_code: '+265',
        code: 'MW',
        currency: 'MWK',
        name: 'Malawi',
    },
    {
        calling_code: '+960',
        code: 'MV',
        currency: 'MVR',
        name: 'Maldives',
    },
    {
        calling_code: '+222',
        code: 'MR',
        currency: 'MRO',
        name: 'Mauritania',
    },
    {
        calling_code: '+256',
        code: 'UG',
        currency: 'UGX',
        name: 'Uganda',
    },
    {
        calling_code: '+255',
        code: 'TZ',
        currency: 'TZS',
        name: 'Tanzania',
    },
    {
        calling_code: '+60',
        code: 'MY',
        currency: 'MYR',
        name: 'Malaysia',
    },
    {
        calling_code: '+52',
        code: 'MX',
        currency: 'MXN',
        name: 'Mexico',
    },
    {
        calling_code: '+972',
        code: 'IL',
        currency: 'ILS',
        name: 'Israel',
    },
    {
        calling_code: '+33',
        code: 'FR',
        currency: 'EUR',
        name: 'France',
    },
    {
        calling_code: '+358',
        code: 'FI',
        currency: 'EUR',
        name: 'Finland',
    },
    {
        calling_code: '+679',
        code: 'FJ',
        currency: 'FJD',
        name: 'Fiji',
    },
    {
        calling_code: '+505',
        code: 'NI',
        currency: 'NIO',
        name: 'Nicaragua',
    },
    {
        calling_code: '+31',
        code: 'NL',
        currency: 'EUR',
        name: 'Netherlands',
    },
    {
        calling_code: '+47',
        code: 'NO',
        currency: 'NOK',
        name: 'Norway',
    },
    {
        calling_code: '+264',
        code: 'NA',
        currency: 'NAD',
        name: 'Namibia',
    },
    {
        calling_code: '+678',
        code: 'VU',
        currency: 'VUV',
        name: 'Vanuatu',
    },
    {
        calling_code: '+227',
        code: 'NE',
        currency: 'XOF',
        name: 'Niger',
    },
    {
        calling_code: '+234',
        code: 'NG',
        currency: 'NGN',
        name: 'Nigeria',
    },
    {
        calling_code: '+64',
        code: 'NZ',
        currency: 'NZD',
        name: 'New Zealand',
    },
    {
        calling_code: '+977',
        code: 'NP',
        currency: 'NPR',
        name: 'Nepal',
    },
    {
        calling_code: '+674',
        code: 'NR',
        currency: 'AUD',
        name: 'Nauru',
    },
    {
        calling_code: '+383',
        code: 'XK',
        currency: 'EUR',
        name: 'Kosovo',
    },
    {
        calling_code: '+225',
        code: 'CI',
        currency: 'XOF',
        name: 'Ivory Coast',
    },
    {
        calling_code: '+41',
        code: 'CH',
        currency: 'CHF',
        name: 'Switzerland',
    },
    {
        calling_code: '+57',
        code: 'CO',
        currency: 'COP',
        name: 'Colombia',
    },
    {
        calling_code: '+86',
        code: 'CN',
        currency: 'CNY',
        name: 'China',
    },
    {
        calling_code: '+237',
        code: 'CM',
        currency: 'XAF',
        name: 'Cameroon',
    },
    {
        calling_code: '+56',
        code: 'CL',
        currency: 'CLP',
        name: 'Chile',
    },
    {
        calling_code: '+1',
        code: 'CA',
        currency: 'CAD',
        name: 'Canada',
    },
    {
        calling_code: '+242',
        code: 'CG',
        currency: 'XAF',
        name: 'Congo',
    },
    {
        calling_code: '+236',
        code: 'CF',
        currency: 'XAF',
        name: 'Central African Republic',
    },
    {
        calling_code: '+243',
        code: 'CD',
        currency: 'CDF',
        name: 'Democratic Republic of the Congo',
    },
    {
        calling_code: '+420',
        code: 'CZ',
        currency: 'CZK',
        name: 'Czech Republic',
    },
    {
        calling_code: '+357',
        code: 'CY',
        currency: 'EUR',
        name: 'Cyprus',
    },
    {
        calling_code: '+506',
        code: 'CR',
        currency: 'CRC',
        name: 'Costa Rica',
    },
    {
        calling_code: '+238',
        code: 'CV',
        currency: 'CVE',
        name: 'Cape Verde',
    },
    {
        calling_code: '+53',
        code: 'CU',
        currency: 'CUP',
        name: 'Cuba',
    },
    {
        calling_code: '+268',
        code: 'SZ',
        currency: 'SZL',
        name: 'Swaziland',
    },
    {
        calling_code: '+963',
        code: 'SY',
        currency: 'SYP',
        name: 'Syria',
    },
    {
        calling_code: '+996',
        code: 'KG',
        currency: 'KGS',
        name: 'Kyrgyzstan',
    },
    {
        calling_code: '+254',
        code: 'KE',
        currency: 'KES',
        name: 'Kenya',
    },
    {
        calling_code: '+211',
        code: 'SS',
        currency: 'SSP',
        name: 'South Sudan',
    },
    {
        calling_code: '+597',
        code: 'SR',
        currency: 'SRD',
        name: 'Suriname',
    },
    {
        calling_code: '+686',
        code: 'KI',
        currency: 'AUD',
        name: 'Kiribati',
    },
    {
        calling_code: '+855',
        code: 'KH',
        currency: 'KHR',
        name: 'Cambodia',
    },
    {
        calling_code: '+1-869',
        code: 'KN',
        currency: 'XCD',
        name: 'Saint Kitts and Nevis',
    },
    {
        calling_code: '+269',
        code: 'KM',
        currency: 'KMF',
        name: 'Comoros',
    },
    {
        calling_code: '+239',
        code: 'ST',
        currency: 'STD',
        name: 'Sao Tome and Principe',
    },
    {
        calling_code: '+421',
        code: 'SK',
        currency: 'EUR',
        name: 'Slovakia',
    },
    {
        calling_code: '+82',
        code: 'KR',
        currency: 'KRW',
        name: 'South Korea',
    },
    {
        calling_code: '+386',
        code: 'SI',
        currency: 'EUR',
        name: 'Slovenia',
    },
    {
        calling_code: '+850',
        code: 'KP',
        currency: 'KPW',
        name: 'North Korea',
    },
    {
        calling_code: '+965',
        code: 'KW',
        currency: 'KWD',
        name: 'Kuwait',
    },
    {
        calling_code: '+221',
        code: 'SN',
        currency: 'XOF',
        name: 'Senegal',
    },
    {
        calling_code: '+378',
        code: 'SM',
        currency: 'EUR',
        name: 'San Marino',
    },
    {
        calling_code: '+232',
        code: 'SL',
        currency: 'SLL',
        name: 'Sierra Leone',
    },
    {
        calling_code: '+248',
        code: 'SC',
        currency: 'SCR',
        name: 'Seychelles',
    },
    {
        calling_code: '+7',
        code: 'KZ',
        currency: 'KZT',
        name: 'Kazakhstan',
    },
    {
        calling_code: '+65',
        code: 'SG',
        currency: 'SGD',
        name: 'Singapore',
    },
    {
        calling_code: '+46',
        code: 'SE',
        currency: 'SEK',
        name: 'Sweden',
    },
    {
        calling_code: '+249',
        code: 'SD',
        currency: 'SDG',
        name: 'Sudan',
    },
    {
        calling_code: '+1-809',
        code: 'DO',
        currency: 'DOP',
        name: 'Dominican Republic',
    },
    {
        calling_code: '+1-767',
        code: 'DM',
        currency: 'XCD',
        name: 'Dominica',
    },
    {
        calling_code: '+253',
        code: 'DJ',
        currency: 'DJF',
        name: 'Djibouti',
    },
    {
        calling_code: '+45',
        code: 'DK',
        currency: 'DKK',
        name: 'Denmark',
    },
    {
        calling_code: '+49',
        code: 'DE',
        currency: 'EUR',
        name: 'Germany',
    },
    {
        calling_code: '+967',
        code: 'YE',
        currency: 'YER',
        name: 'Yemen',
    },
    {
        calling_code: '+213',
        code: 'DZ',
        currency: 'DZD',
        name: 'Algeria',
    },
    {
        calling_code: '+1',
        code: 'US',
        currency: 'USD',
        name: 'United States',
    },
    {
        calling_code: '+598',
        code: 'UY',
        currency: 'UYU',
        name: 'Uruguay',
    },
    {
        calling_code: '+961',
        code: 'LB',
        currency: 'LBP',
        name: 'Lebanon',
    },
    {
        calling_code: '+1-758',
        code: 'LC',
        currency: 'XCD',
        name: 'Saint Lucia',
    },
    {
        calling_code: '+856',
        code: 'LA',
        currency: 'LAK',
        name: 'Laos',
    },
    {
        calling_code: '+688',
        code: 'TV',
        currency: 'AUD',
        name: 'Tuvalu',
    },
    {
        calling_code: '+886',
        code: 'TW',
        currency: 'TWD',
        name: 'Taiwan',
    },
    {
        calling_code: '+1-868',
        code: 'TT',
        currency: 'TTD',
        name: 'Trinidad and Tobago',
    },
    {
        calling_code: '+90',
        code: 'TR',
        currency: 'TRY',
        name: 'Turkey',
    },
    {
        calling_code: '+94',
        code: 'LK',
        currency: 'LKR',
        name: 'Sri Lanka',
    },
    {
        calling_code: '+423',
        code: 'LI',
        currency: 'CHF',
        name: 'Liechtenstein',
    },
    {
        calling_code: '+371',
        code: 'LV',
        currency: 'EUR',
        name: 'Latvia',
    },
    {
        calling_code: '+676',
        code: 'TO',
        currency: 'TOP',
        name: 'Tonga',
    },
    {
        calling_code: '+370',
        code: 'LT',
        currency: 'LTL',
        name: 'Lithuania',
    },
    {
        calling_code: '+352',
        code: 'LU',
        currency: 'EUR',
        name: 'Luxembourg',
    },
    {
        calling_code: '+231',
        code: 'LR',
        currency: 'LRD',
        name: 'Liberia',
    },
    {
        calling_code: '+266',
        code: 'LS',
        currency: 'LSL',
        name: 'Lesotho',
    },
    {
        calling_code: '+66',
        code: 'TH',
        currency: 'THB',
        name: 'Thailand',
    },
    {
        calling_code: '+228',
        code: 'TG',
        currency: 'XOF',
        name: 'Togo',
    },
    {
        calling_code: '+235',
        code: 'TD',
        currency: 'XAF',
        name: 'Chad',
    },
    {
        calling_code: '+218',
        code: 'LY',
        currency: 'LYD',
        name: 'Libya',
    },
    {
        calling_code: '+1-784',
        code: 'VC',
        currency: 'XCD',
        name: 'Saint Vincent and the Grenadines',
    },
    {
        calling_code: '+971',
        code: 'AE',
        currency: 'AED',
        name: 'United Arab Emirates',
    },
    {
        calling_code: '+376',
        code: 'AD',
        currency: 'EUR',
        name: 'Andorra',
    },
    {
        calling_code: '+1-268',
        code: 'AG',
        currency: 'XCD',
        name: 'Antigua and Barbuda',
    },
    {
        calling_code: '+93',
        code: 'AF',
        currency: 'AFN',
        name: 'Afghanistan',
    },
    {
        calling_code: '+354',
        code: 'IS',
        currency: 'ISK',
        name: 'Iceland',
    },
    {
        calling_code: '+98',
        code: 'IR',
        currency: 'IRR',
        name: 'Iran',
    },
    {
        calling_code: '+374',
        code: 'AM',
        currency: 'AMD',
        name: 'Armenia',
    },
    {
        calling_code: '+355',
        code: 'AL',
        currency: 'ALL',
        name: 'Albania',
    },
    {
        calling_code: '+244',
        code: 'AO',
        currency: 'AOA',
        name: 'Angola',
    },
    {
        calling_code: '+54',
        code: 'AR',
        currency: 'ARS',
        name: 'Argentina',
    },
    {
        calling_code: '+61',
        code: 'AU',
        currency: 'AUD',
        name: 'Australia',
    },
    {
        calling_code: '+43',
        code: 'AT',
        currency: 'EUR',
        name: 'Austria',
    },
    {
        calling_code: '+91',
        code: 'IN',
        currency: 'INR',
        name: 'India',
    },
    {
        calling_code: '+994',
        code: 'AZ',
        currency: 'AZN',
        name: 'Azerbaijan',
    },
    {
        calling_code: '+353',
        code: 'IE',
        currency: 'EUR',
        name: 'Ireland',
    },
    {
        calling_code: '+62',
        code: 'ID',
        currency: 'IDR',
        name: 'Indonesia',
    },
    {
        calling_code: '+380',
        code: 'UA',
        currency: 'UAH',
        name: 'Ukraine',
    },
    {
        calling_code: '+974',
        code: 'QA',
        currency: 'QAR',
        name: 'Qatar',
    },
    {
        calling_code: '+258',
        code: 'MZ',
        currency: 'MZN',
        name: 'Mozambique',
    },
];

export const mswCreateBusiness: CreateBusinessResponse = {
    business_pk: '1',
}

export const mswSubscriptions = [
    // {
    //     id: 'essential',
    //     name: 'Essential',
    //     order: 2,
    //     features: {
    //         appointments_reminders: 'Limited',
    //         fidelity_program: 'Upcoming',
    //         free_business_sign: 'Disabled',
    //         immediate_access_to_new_features: 'Enabled',
    //         integrated_chat: 'Upcoming',
    //         integrated_shop: 'Upcoming',
    //         is_mobile_app_available: 'Disabled',
    //         multiple_locations: 'Enabled',
    //         reports_and_analytics: 'Enabled',
    //         priority_support: 'Limited',
    //         theme_customization: 'Limited',
    //         unlimited_appointments: 'Enabled',
    //         unlimited_clients: 'Enabled',
    //         website: 'Enabled',
    //     },
    // },
    {
        id: 'all_in_one',
        name: 'All-In-One',
        order: 1,
        features: {
            appointments_reminders: 'Enabled',
            fidelity_program: 'Upcoming',
            free_business_sign: 'Enabled',
            immediate_access_to_new_features: 'Enabled',
            integrated_chat: 'Upcoming',
            integrated_shop: 'Upcoming',
            is_mobile_app_available: 'Enabled',
            multiple_locations: 'Enabled',
            reports_and_analytics: 'Enabled',
            priority_support: 'Enabled',
            theme_customization: 'Enabled',
            unlimited_appointments: 'Enabled',
            unlimited_clients: 'Enabled',
            website: 'Enabled',
        },
    },
];

export const mswSubscribe: SubscriptionResponse = {
    features: {
        appointments_reminders: SubscriptionPlanFeatureStatus.Enabled,
        fidelity_program: SubscriptionPlanFeatureStatus.Upcoming,
        free_business_sign: SubscriptionPlanFeatureStatus.Enabled,
        immediate_access_to_new_features:
            SubscriptionPlanFeatureStatus.Disabled,
        integrated_chat: SubscriptionPlanFeatureStatus.Upcoming,
        integrated_shop: SubscriptionPlanFeatureStatus.Upcoming,
        is_mobile_app_available: SubscriptionPlanFeatureStatus.Enabled,
        multiple_locations: SubscriptionPlanFeatureStatus.Enabled,
        reports_and_analytics: SubscriptionPlanFeatureStatus.Enabled,
        priority_support: SubscriptionPlanFeatureStatus.Enabled,
        theme_customization: SubscriptionPlanFeatureStatus.Enabled,
        unlimited_appointments: SubscriptionPlanFeatureStatus.Enabled,
        unlimited_clients: SubscriptionPlanFeatureStatus.Enabled,
        website: SubscriptionPlanFeatureStatus.Enabled,
    },
    id: SubscriptionId.Essential,
    order: 1,
    name: 'Essential',
};

export const mswThemeStyles: ThemeStyle[] = [
    {
        code: 'brand-colors',
        name: 'Brand Colors',
    },
    {
        code: 'be-like-rose',
        name: 'Be Like Rose',
    },
    {
        code: 'i-love-black',
        name: 'I Love Black',
    },
    {
        code: 'fresh-mint',
        name: 'Fresh Mint',
    },
];

export const mswTimezones: Timezone[] = [
    {
        gmt: '-12:00',
        name: 'International Date Line West',
        zoneName: 'Etc/GMT+12',
    },
    {
        gmt: '-11:00',
        name: 'Midway Island, Samoa',
        zoneName: 'Pacific/Midway',
    },
    {
        gmt: '-10:00',
        name: 'Hawaii',
        zoneName: 'Pacific/Honolulu',
    },
    {
        gmt: '-09:00',
        name: 'Alaska',
        zoneName: 'US/Alaska',
    },
    {
        gmt: '-08:00',
        name: 'Pacific Time (US & Canada)',
        zoneName: 'America/Los_Angeles',
    },
    {
        gmt: '-08:00',
        name: 'Tijuana, Baja California',
        zoneName: 'America/Tijuana',
    },
    {
        gmt: '-07:00',
        name: 'Arizona',
        zoneName: 'US/Arizona',
    },
    {
        gmt: '-07:00',
        name: 'Chihuahua, La Paz, Mazatlan',
        zoneName: 'America/Chihuahua',
    },
    {
        gmt: '-07:00',
        name: 'Mountain Time (US & Canada)',
        zoneName: 'US/Mountain',
    },
    {
        gmt: '-06:00',
        name: 'Central America',
        zoneName: 'America/Managua',
    },
    {
        gmt: '-06:00',
        name: 'Central Time (US & Canada)',
        zoneName: 'US/Central',
    },
    {
        gmt: '-06:00',
        name: 'Guadalajara, Mexico City, Monterrey',
        zoneName: 'America/Mexico_City',
    },
    {
        gmt: '-06:00',
        name: 'Saskatchewan',
        zoneName: 'Canada/Saskatchewan',
    },
    {
        gmt: '-05:00',
        name: 'Bogota, Lima, Quito, Rio Branco',
        zoneName: 'America/Bogota',
    },
    {
        gmt: '-05:00',
        name: 'Eastern Time (US & Canada)',
        zoneName: 'US/Eastern',
    },
    {
        gmt: '-05:00',
        name: 'Indiana (East)',
        zoneName: 'US/East-Indiana',
    },
    {
        gmt: '-04:00',
        name: 'Atlantic Time (Canada)',
        zoneName: 'Canada/Atlantic',
    },
    {
        gmt: '-04:00',
        name: 'Caracas, La Paz',
        zoneName: 'America/Caracas',
    },
    {
        gmt: '-04:00',
        name: 'Manaus',
        zoneName: 'America/Manaus',
    },
    {
        gmt: '-04:00',
        name: 'Santiago',
        zoneName: 'America/Santiago',
    },
    {
        gmt: '-03:30',
        name: 'Newfoundland',
        zoneName: 'Canada/Newfoundland',
    },
    {
        gmt: '-03:00',
        name: 'Brasilia',
        zoneName: 'America/Sao_Paulo',
    },
    {
        gmt: '-03:00',
        name: 'Buenos Aires, Georgetown',
        zoneName: 'America/Argentina/Buenos_Aires',
    },
    {
        gmt: '-03:00',
        name: 'Greenland',
        zoneName: 'America/Godthab',
    },
    {
        gmt: '-03:00',
        name: 'Montevideo',
        zoneName: 'America/Montevideo',
    },
    {
        gmt: '-02:00',
        name: 'Mid-Atlantic',
        zoneName: 'America/Noronha',
    },
    {
        gmt: '-01:00',
        name: 'Cape Verde Is.',
        zoneName: 'Atlantic/Cape_Verde',
    },
    {
        gmt: '-01:00',
        name: 'Azores',
        zoneName: 'Atlantic/Azores',
    },
    {
        gmt: '+00:00',
        name: 'Casablanca, Monrovia, Reykjavik',
        zoneName: 'Africa/Casablanca',
    },
    {
        gmt: '+00:00',
        name: 'Greenwich Mean Time : Dublin, Edinburgh, Lisbon, London',
        zoneName: 'Etc/Greenwich',
    },
    {
        gmt: '+01:00',
        name: 'Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna',
        zoneName: 'Europe/Amsterdam',
    },
    {
        gmt: '+01:00',
        name: 'Belgrade, Bratislava, Budapest, Ljubljana, Prague',
        zoneName: 'Europe/Belgrade',
    },
    {
        gmt: '+01:00',
        name: 'Brussels, Copenhagen, Madrid, Paris',
        zoneName: 'Europe/Brussels',
    },
    {
        gmt: '+01:00',
        name: 'Sarajevo, Skopje, Warsaw, Zagreb',
        zoneName: 'Europe/Sarajevo',
    },
    {
        gmt: '+01:00',
        name: 'West Central Africa',
        zoneName: 'Africa/Lagos',
    },
    {
        gmt: '+02:00',
        name: 'Amman',
        zoneName: 'Asia/Amman',
    },
    {
        gmt: '+02:00',
        name: 'Athens, Bucharest, Istanbul',
        zoneName: 'Europe/Athens',
    },
    {
        gmt: '+02:00',
        name: 'Beirut',
        zoneName: 'Asia/Beirut',
    },
    {
        gmt: '+02:00',
        name: 'Cairo',
        zoneName: 'Africa/Cairo',
    },
    {
        gmt: '+02:00',
        name: 'Harare, Pretoria',
        zoneName: 'Africa/Harare',
    },
    {
        gmt: '+02:00',
        name: 'Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius',
        zoneName: 'Europe/Helsinki',
    },
    {
        gmt: '+02:00',
        name: 'Jerusalem',
        zoneName: 'Asia/Jerusalem',
    },
    {
        gmt: '+02:00',
        name: 'Minsk',
        zoneName: 'Europe/Minsk',
    },
    {
        gmt: '+02:00',
        name: 'Windhoek',
        zoneName: 'Africa/Windhoek',
    },
    {
        gmt: '+03:00',
        name: 'Kuwait, Riyadh, Baghdad',
        zoneName: 'Asia/Kuwait',
    },
    {
        gmt: '+03:00',
        name: 'Moscow, St. Petersburg, Volgograd',
        zoneName: 'Europe/Moscow',
    },
    {
        gmt: '+03:00',
        name: 'Nairobi',
        zoneName: 'Africa/Nairobi',
    },
    {
        gmt: '+03:00',
        name: 'Tbilisi',
        zoneName: 'Asia/Tbilisi',
    },
    {
        gmt: '+03:30',
        name: 'Tehran',
        zoneName: 'Asia/Tehran',
    },
    {
        gmt: '+04:00',
        name: 'Abu Dhabi, Muscat',
        zoneName: 'Asia/Muscat',
    },
    {
        gmt: '+04:00',
        name: 'Baku',
        zoneName: 'Asia/Baku',
    },
    {
        gmt: '+04:00',
        name: 'Yerevan',
        zoneName: 'Asia/Yerevan',
    },
    {
        gmt: '+04:30',
        name: 'Kabul',
        zoneName: 'Asia/Kabul',
    },
    {
        gmt: '+05:00',
        name: 'Yekaterinburg',
        zoneName: 'Asia/Yekaterinburg',
    },
    {
        gmt: '+05:00',
        name: 'Islamabad, Karachi, Tashkent',
        zoneName: 'Asia/Karachi',
    },
    {
        gmt: '+05:30',
        name: 'Chennai, Kolkata, Mumbai, New Delhi, India',
        zoneName: 'Asia/Kolkata',
    },
    {
        gmt: '+05:30',
        name: 'Sri Jayawardenapura, Sri Lanka',
        zoneName: 'Asia/Colombo',
    },
    {
        gmt: '+05:45',
        name: 'Kathmandu',
        zoneName: 'Asia/Katmandu',
    },
    {
        gmt: '+06:00',
        name: 'Almaty, Novosibirsk',
        zoneName: 'Asia/Almaty',
    },
    {
        gmt: '+06:00',
        name: 'Astana, Dhaka',
        zoneName: 'Asia/Dhaka',
    },
    {
        gmt: '+06:30',
        name: 'Yangon (Rangoon)',
        zoneName: 'Asia/Rangoon',
    },
    {
        gmt: '+07:00',
        name: 'Bangkok, Hanoi, Jakarta',
        zoneName: 'Asia/Bangkok',
    },
    {
        gmt: '+07:00',
        name: 'Krasnoyarsk',
        zoneName: 'Asia/Krasnoyarsk',
    },
    {
        gmt: '+08:00',
        name: 'Beijing, Chongqing, Hong Kong, Urumqi',
        zoneName: 'Asia/Hong_Kong',
    },
    {
        gmt: '+08:00',
        name: 'Kuala Lumpur, Singapore',
        zoneName: 'Asia/Kuala_Lumpur',
    },
    {
        gmt: '+08:00',
        name: 'Irkutsk, Ulaan Bataar',
        zoneName: 'Asia/Irkutsk',
    },
    {
        gmt: '+08:00',
        name: 'Perth',
        zoneName: 'Australia/Perth',
    },
    {
        gmt: '+08:00',
        name: 'Taipei',
        zoneName: 'Asia/Taipei',
    },
    {
        gmt: '+09:00',
        name: 'Osaka, Sapporo, Tokyo',
        zoneName: 'Asia/Tokyo',
    },
    {
        gmt: '+09:00',
        name: 'Seoul',
        zoneName: 'Asia/Seoul',
    },
    {
        gmt: '+09:00',
        name: 'Yakutsk',
        zoneName: 'Asia/Yakutsk',
    },
    {
        gmt: '+09:30',
        name: 'Adelaide',
        zoneName: 'Australia/Adelaide',
    },
    {
        gmt: '+09:30',
        name: 'Darwin',
        zoneName: 'Australia/Darwin',
    },
    {
        gmt: '+10:00',
        name: 'Brisbane',
        zoneName: 'Australia/Brisbane',
    },
    {
        gmt: '+10:00',
        name: 'Canberra, Melbourne, Sydney',
        zoneName: 'Australia/Canberra',
    },
    {
        gmt: '+10:00',
        name: 'Hobart',
        zoneName: 'Australia/Hobart',
    },
    {
        gmt: '+10:00',
        name: 'Guam, Port Moresby',
        zoneName: 'Pacific/Guam',
    },
    {
        gmt: '+10:00',
        name: 'Vladivostok',
        zoneName: 'Asia/Vladivostok',
    },
    {
        gmt: '+11:00',
        name: 'Magadan, Solomon Is., New Caledonia',
        zoneName: 'Asia/Magadan',
    },
    {
        gmt: '+12:00',
        name: 'Auckland, Wellington',
        zoneName: 'Pacific/Auckland',
    },
    {
        gmt: '+12:00',
        name: 'Fiji, Kamchatka, Marshall Is.',
        zoneName: 'Pacific/Fiji',
    },
    {
        gmt: '+13:00',
        name: "Nuku'alofa",
        zoneName: 'Pacific/Tongatapu',
    },
];

export const mswPaypalSubscriptionPlans = {
    plans: [
        {
            id: 'P-1RD80591A82092240M3LHEJQ',
            version: 1,
            product_id: 'bookingappbusiness',
            name: 'essential_monthly',
            status: 'ACTIVE',
            description: 'Essential Monthly Plan',
            usage_type: 'LICENSED',
            billing_cycles: [
                {
                    pricing_scheme: {
                        version: 1,
                        fixed_price: {
                            currency_code: 'USD',
                            value: '34.99',
                        },
                        create_time: '2024-09-03T02:19:18Z',
                        update_time: '2024-09-03T02:19:18Z',
                    },
                    frequency: {
                        interval_unit: 'MONTH',
                        interval_count: 1,
                    },
                    tenure_type: 'REGULAR',
                    sequence: 1,
                    total_cycles: 0,
                },
            ],
            payment_preferences: {
                service_type: 'PREPAID',
                auto_bill_outstanding: true,
                setup_fee: {
                    currency_code: 'USD',
                    value: '0.0',
                },
                setup_fee_failure_action: 'CONTINUE',
                payment_failure_threshold: 1,
            },
            quantity_supported: false,
            payee: {
                merchant_id: 'VFJVGGENRQRQE',
                display_data: {
                    business_email: 'cs-sb-1gmyy32353871@business.example.com',
                },
            },
            create_time: '2024-09-03T02:19:18Z',
            update_time: '2024-09-04T01:13:37Z',
            links: [
                {
                    href: 'https://api.sandbox.paypal.com/v1/billing/plans/P-1RD80591A82092240M3LHEJQ',
                    rel: 'self',
                    method: 'GET',
                    encType: 'application/json',
                },
            ],
        },
        {
            id: 'P-4JR7974776967824HM3LHEZQ',
            version: 1,
            product_id: 'bookingappbusiness',
            name: 'essential_yearly',
            status: 'ACTIVE',
            description: 'Essential Yearly Plan',
            usage_type: 'LICENSED',
            billing_cycles: [
                {
                    pricing_scheme: {
                        version: 1,
                        fixed_price: {
                            currency_code: 'USD',
                            value: '379.0',
                        },
                        create_time: '2024-09-03T02:20:22Z',
                        update_time: '2024-09-03T02:20:22Z',
                    },
                    frequency: {
                        interval_unit: 'YEAR',
                        interval_count: 1,
                    },
                    tenure_type: 'REGULAR',
                    sequence: 1,
                    total_cycles: 0,
                },
            ],
            payment_preferences: {
                service_type: 'PREPAID',
                auto_bill_outstanding: true,
                setup_fee: {
                    currency_code: 'USD',
                    value: '0.0',
                },
                setup_fee_failure_action: 'CONTINUE',
                payment_failure_threshold: 1,
            },
            quantity_supported: false,
            payee: {
                merchant_id: 'VFJVGGENRQRQE',
                display_data: {
                    business_email: 'cs-sb-1gmyy32353871@business.example.com',
                },
            },
            create_time: '2024-09-03T02:20:22Z',
            update_time: '2024-09-04T01:13:19Z',
            links: [
                {
                    href: 'https://api.sandbox.paypal.com/v1/billing/plans/P-4JR7974776967824HM3LHEZQ',
                    rel: 'self',
                    method: 'GET',
                    encType: 'application/json',
                },
            ],
        },
        {
            id: 'P-1VH27550DP090781TM3LHFFY',
            version: 1,
            product_id: 'bookingappbusiness',
            name: 'all_in_one_yearly',
            status: 'ACTIVE',
            description: 'All-in-one Yearly Plan',
            usage_type: 'LICENSED',
            billing_cycles: [
                {
                    pricing_scheme: {
                        version: 1,
                        fixed_price: {
                            currency_code: 'USD',
                            value: '759.0',
                        },
                        create_time: '2024-09-03T02:21:11Z',
                        update_time: '2024-09-03T02:21:11Z',
                    },
                    frequency: {
                        interval_unit: 'YEAR',
                        interval_count: 1,
                    },
                    tenure_type: 'REGULAR',
                    sequence: 1,
                    total_cycles: 0,
                },
            ],
            payment_preferences: {
                service_type: 'PREPAID',
                auto_bill_outstanding: true,
                setup_fee: {
                    currency_code: 'USD',
                    value: '0.0',
                },
                setup_fee_failure_action: 'CONTINUE',
                payment_failure_threshold: 1,
            },
            quantity_supported: false,
            payee: {
                merchant_id: 'VFJVGGENRQRQE',
                display_data: {
                    business_email: 'cs-sb-1gmyy32353871@business.example.com',
                },
            },
            create_time: '2024-09-03T02:21:11Z',
            update_time: '2024-09-04T01:12:51Z',
            links: [
                {
                    href: 'https://api.sandbox.paypal.com/v1/billing/plans/P-1VH27550DP090781TM3LHFFY',
                    rel: 'self',
                    method: 'GET',
                    encType: 'application/json',
                },
            ],
        },
        {
            id: 'P-10L03858S3301502NM3LHFSQ',
            version: 1,
            product_id: 'bookingappbusiness',
            name: 'all_in_one_monthly',
            status: 'ACTIVE',
            description: 'All-in-one Monthly Plan',
            usage_type: 'LICENSED',
            billing_cycles: [
                {
                    pricing_scheme: {
                        version: 1,
                        fixed_price: {
                            currency_code: 'USD',
                            value: '69.99',
                        },
                        create_time: '2024-09-03T02:22:02Z',
                        update_time: '2024-09-03T02:22:02Z',
                    },
                    frequency: {
                        interval_unit: 'MONTH',
                        interval_count: 1,
                    },
                    tenure_type: 'REGULAR',
                    sequence: 1,
                    total_cycles: 0,
                },
            ],
            payment_preferences: {
                service_type: 'PREPAID',
                auto_bill_outstanding: true,
                setup_fee: {
                    currency_code: 'USD',
                    value: '0.0',
                },
                setup_fee_failure_action: 'CONTINUE',
                payment_failure_threshold: 1,
            },
            quantity_supported: false,
            payee: {
                merchant_id: 'VFJVGGENRQRQE',
                display_data: {
                    business_email: 'cs-sb-1gmyy32353871@business.example.com',
                },
            },
            create_time: '2024-09-03T02:22:02Z',
            update_time: '2024-09-06T04:07:09Z',
            links: [
                {
                    href: 'https://api.sandbox.paypal.com/v1/billing/plans/P-10L03858S3301502NM3LHFSQ',
                    rel: 'self',
                    method: 'GET',
                    encType: 'application/json',
                },
            ],
        },
    ],
    links: [
        {
            href: 'https://api.sandbox.paypal.com/v1/billing/plans?page_size=10&page=1',
            rel: 'self',
            method: 'GET',
            encType: 'application/json',
        },
    ],
};

export const mswPaypalAuthentication: PaypalGenerateAccessToken = {
    access_token: 'A21AAHc7',
    app_id: 'APP-80W284485P519543T',
    expires_in: 32400,
    token_type: 'Bearer',
    nonce: '2024-09-14T05:25:23.520Z',
    scope: 'https://uri.paypal.com/services/invoicing https://uri.paypal.com/services/disputes/read-buyer https://uri.paypal.com/services/disputes/update-seller https://uri.paypal.com/services/payments/realtimepayment https://uri.paypal.com/services/disputes/read-seller https://uri.paypal.com/services/payments/payment/authcapture openid https://uri.paypal.com/services/disputes/update-buyer',
};
