require 'dotenv/load'
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    setup_circle_ci
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    match(
      type: "appstore", 
      readonly: true, 
      git_url: ENV["FASTLANE_MATCH_GIT_SSH_URL"]
    )

    
    app_store_connect_api_key(
      key_id: ENV["FASTLANE_APP_STORE_CONNECT_API_KEY_ID"],
      is_key_content_base64: true,
      issuer_id: ENV["FASTLANE_APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["FASTLANE_APP_STORE_CONNECT_KEY_CONTENT"],
      duration: 1200, # optional (maximum 1200)
      in_house: false # optional but may be required if using match/sigh
    )

    latest_testflight_build_number = latest_testflight_build_number(
      app_identifier: "com.boclar.bookingappbusiness",
    )

    # latest_build_number = latest_testflight_build_number.to_i + 1
    latest_build_number = ENV["CIRCLE_BUILD_NUM"]

    increment_build_number(
      build_number: latest_build_number,
      xcodeproj: "Boclar.xcodeproj"
    )

    build_app(
      workspace: "Boclar.xcworkspace", 
      scheme: "Boclar",
      export_method: "app-store"
    )
    
    upload_to_testflight(
      # Do not wait more than 5 minutes for processing
      wait_processing_timeout_duration: 5 * 60
    )

    UI.message("Build number: #{latest_build_number}")
  end
end
