require 'dotenv/load'
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Deploy a new version to Google Play Internal Testing"
  lane :beta do
    version_codes = google_play_track_version_codes(
      json_key: ENV['GOOGLE_SERVICE_ACCOUNT_JSON_FILE_PATH'],
      package_name: "com.boclar.bookingappbusiness",
      track: "internal",
    )

    # Extract the version code from the response
    # latest_version_code = version_codes.max + 1
    latest_version_code = ENV["CIRCLE_BUILD_NUM"]

    increment_version_code({
      # version_code: version_codes.max + 1
      version_code: latest_version_code
    })
    
    gradle(
      task: "clean bundleRelease",
      properties: {
        "android.injected.signing.store.file" => ENV['ANDROID_SIGNING_KEYSTORE_FILE_PATH'],
        "android.injected.signing.store.password" => ENV['ANDROID_SIGNING_KEYSTORE_PASSWORD'],
        "android.injected.signing.key.alias" => ENV['ANDROID_SIGNING_KEY_ALIAS'],
        "android.injected.signing.key.password" => ENV['ANDROID_SIGNING_KEY_PASSWORD'],
        # Keep it here, although it's not used. It appears is it not detected by upload_to_play_store when uploading the aab file
        "android.injected.version.code" => latest_version_code,
        "android.injected.version.name" => "Boclar"
      }
    )
    upload_to_play_store(
      aab: "./app/build/outputs/bundle/release/app-release.aab",
      json_key: ENV['GOOGLE_SERVICE_ACCOUNT_JSON_FILE_PATH'],
      release_status: 'draft',
      package_name: "com.boclar.bookingappbusiness",
      track: "internal",
      track_promote_to: "internal",
      version_name: "Boclar",
    )

    UI.message("Version code: #{latest_version_code}")
  end
end
